name: CI/CD

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4  # Updated version

      - name: Setup Python
        uses: actions/setup-python@v5  # Updated version
        with:
          python-version: 3.12.7

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check model file
        run: |
          ls -l
          if [ ! -f model.pkl ]; then echo "❌ model.pkl not found"; exit 1; fi

      - name: Run tests
        run: |
          pip install pytest
          ls -l
          echo "Running tests..."
          if [ -d "tests" ]; then pytest || exit 2; else echo "No tests directory found."; fi

  deploy:
    needs: build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy placeholder
        run: echo "✅ Ready to deploy - add real deploy steps here"
