name: CI/CD

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'  # Chạy mỗi giờ

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3.0.0
        with:
          python-version: 3.12.7

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Weights & Biases
        run: wandb login ${{ secrets.WANDB_KEY_ID }}

      - name: Run tests (if available)
        run: |
          pip install pytest
          if [ -d "tests" ]; then pytest; else echo "No tests directory found."; fi

  deploy:
    needs: build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Simulated Deploy Step
        run: echo "✅ Deployment completed (no SSH used)"
