name: CI/CD

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 * * * *'  # Chạy mỗi giờ

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (if available)
        run: |
          pip install pytest
          if [ -d "tests" ]; then
            pytest
          else
            echo "No tests directory found."
          fi

      - name: Login to Weights & Biases
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_KEY_ID }}
        run: |
          wandb login $WANDB_API_KEY

  deploy:
    needs: build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy placeholder
        run: echo "✅ Ready to deploy - add real deploy steps here"
