name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v3.0.0
        with:
          python-version: 3.12.7

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Weights & Biases
        run: wandb login ${{ secrets.WANDB_KEY_ID }}

      - name: Testing FastAPI
        run: pytest -vv -s


